version: '3'

tasks:
  pdf:
    desc: Generate PDF from LaTeX papers
    deps:
      - pdf:current
      - pdf:trajectory-decomposition

  pdf:current:
    desc: Generate PDF for current paper
    dir: papers
    sources:
      - affine-block-structures.tex
    generates:
      - affine-block-structures.pdf
    cmds:
      - pdflatex -interaction=nonstopmode affine-block-structures.tex
      - pdflatex -interaction=nonstopmode affine-block-structures.tex
    silent: false

  pdf:trajectory-decomposition:
    desc: Generate PDF for trajectory decomposition paper
    dir: papers
    sources:
      - trajectory-decomposition.tex
    generates:
      - trajectory-decomposition.pdf
    cmds:
      - pdflatex -interaction=nonstopmode trajectory-decomposition.tex
      - pdflatex -interaction=nonstopmode trajectory-decomposition.tex
    silent: false

  clean:
    desc: Clean LaTeX auxiliary files
    dir: papers
    cmds:
      - rm -f *.aux *.log *.out *.toc *.synctex.gz

  clean:all:
    desc: Clean all generated files including PDFs
    dir: papers
    cmds:
      - rm -f *.aux *.log *.out *.toc *.synctex.gz *.pdf
