version: '3'

tasks:
  pdf:
    desc: Generate PDF from LaTeX papers
    deps:
      - pdf:current

  pdf:current:
    desc: Generate PDF for current paper
    dir: papers
    sources:
      - affine-block-structures.tex
    generates:
      - affine-block-structures.pdf
    cmds:
      - pdflatex -interaction=nonstopmode affine-block-structures.tex
      - pdflatex -interaction=nonstopmode affine-block-structures.tex
    silent: false

  clean:
    desc: Clean LaTeX auxiliary files
    dir: papers
    cmds:
      - rm -f *.aux *.log *.out *.toc *.synctex.gz

  clean:all:
    desc: Clean all generated files including PDFs
    dir: papers
    cmds:
      - rm -f *.aux *.log *.out *.toc *.synctex.gz *.pdf
